name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      fail-fast: false
      matrix:
        otp: ['25.1']
        elixir: ['1.13.0', '1.13.1', '1.13.2', '1.13.3', '1.13.4', '1.14.0', '1.14.1']
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Get dependencies
        run: make deps

      - name: Check rune format
        run: make fmt_check

      - name: Test rune
        run: make ci

      - name: Build rune
        run: make build
